import card1 from "../public/images/services/card1.png";
import card2 from "../public/images/services/card2.png";
import card3 from "../public/images/services/card3.png";
import card4 from "../public/images/services/card4.png";
import card5 from "../public/images/services/card5.png";
import card6 from "../public/images/services/card6.png";
import card7 from "../public/images/services/card7.png";
import card8 from "../public/images/services/card8.png";
import card9 from "../public/images/services/card9.png";
import card10 from "../public/images/services/card10.png";
import card11 from "../public/images/services/card11.png";
import card12 from "../public/images/services/card12.png";

// Изображения страницы Услуги

import interiorSign from "../public/images/services/interior-signs.png";
import lightBoxes from "../public/images/services/light-boxes.png";
import roofInstall from "../public/images/services/roof-installation.png";
import windowDressing from "../public/images/services/window-dressing.png";
import pilons from "../public/images/services/pilons.png";
import sequins from "../public/images/services/sequins.png";
import slimPanels from "../public/images/services/sm-light-panels.png";
import serviceMain from "../public/images/services/service-main.png";
import laserCutting from "../public/images/services/laser-cutting.png";
import plotterCutting from "../public/images/services/plotter-cutting.png";
import interiorPrint from "../public/images/services/interior-print.png";
import bussinessCard from "../public/images/services/business-card.png";
import flyers from "../public/images/services/flyers.png";
import badges from "../public/images/services/badges.png";
import calendars from "../public/images/services/calendars.png";
import plasticCards from "../public/images/services/plastic-cards.png";
import menus from "../public/images/services/menus.png";
import souvenirs from "../public/images/services/souvenirs.png";
import packets from "../public/images/services/package.png";
import digitalPrint from "../public/images/services/digital-printing.png";
import offsetPrint from "../public/images/services/offset-print.png";

export const indexServices = [
	{
		image: card1,
		alt: "card1",
		text: "Вывески",
		logo: "images/banner-icon.svg",
		color: "rgba(235, 167, 7, 0.79)",
		path: "/services/signboards",
		price: "от 5 000 руб",
	},
	{
		image: card2,
		alt: "card2",
		text: "Объёмные буквы",
		logo: "images/text-icon.svg",
		color: "rgba(62, 53, 36, 0.79)",
		path: "services/volume-letters",
		price: "от 60 руб/см",
	},
	{
		image: card3,
		alt: "card3",
		text: "Гибкий неон",
		logo: "images/neon-icon.svg",
		color: "rgba(80, 10, 10, 0.79)",
		path: "services/flexible-neon",
		price: "от 2000 руб",
	},
	{
		image: card4,
		alt: "card4",
		text: "Согласование рекламы",
		logo: "images/adv-icon.svg",
		color: "rgba(142, 149, 13, 0.79)",
		path: "services/advertion-production",
		price: "от 1 000 руб",
	},
	{
		image: card5,
		alt: "card5",
		text: "Брендирование транспорта",
		logo: "images/brand-icon.svg",
		color: "rgba(0, 59, 78, 0.79)",
		path: "services/branding-transport",
		price: "от 1500 руб",
	},
	{
		image: card6,
		alt: "card6",
		text: "Стенды",
		logo: "images/billboard-icon.svg",
		color: "rgba(20, 23, 51, 0.79)",
		path: "services/stands",
		price: "от 1000 руб",
	},
	{
		image: card7,
		alt: "card7",
		text: "УФ печать",
		logo: "images/print-icon.svg",
		color: "rgba(95, 23, 152, 0.79)",
		path: "services/uv-print",
		price: "от 500 руб",
	},
	{
		image: card8,
		alt: "card8",
		text: "Широко-форматная печать",
		logo: "images/wideprint-icon.svg",
		color: "rgba(0, 172, 216, 0.79)",
		path: "services/widescreen-print",
		price: "от 300 руб",
	},
	{
		image: card9,
		alt: "card9",
		text: "Наклейки",
		logo: "images/sticker-icon.svg",
		color: "rgba(55, 103, 63, 0.79)",
		path: "services/stickers",
		price: "от 10 руб/шт",
	},
	{
		image: card10,
		alt: "card10",
		text: "Таблички",
		logo: "images/table-icon.svg",
		color: "rgba(57, 97, 100, 0.79)",
		path: "services/tables",
		price: "от 300 руб",
	},
	{
		image: card11,
		alt: "card11",
		text: "Фрезеровка",
		logo: "images/milling-icon.svg",
		color: "rgba(118, 71, 0, 0.79)",
		path: "services/milling",
		price: "от 30 руб",
	},
	{
		image: card12,
		alt: "card12",
		text: "Панель-кронштейны",
		logo: "images/bracket-icon.svg",
		color: "rgba(20, 23, 51, 0.79)",
		path: "services/panel-brackets",
		price: "от 8 000 руб",
	},
];

export const serviceTypes = [
	{
		theme: "dark",
		textTheme: "text-white",
		direction: "flex-row",
		titleSize: "large",
		titleColSize: "col-lg-6",
		title: "Производство рекламы",
		id: "advertion-production",
		list: [
			{
				image: card1,
				alt: "card1",
				text: "Вывески",
				logo: "",
				color: "rgba(235, 167, 7, 0.79)",
				path: "services/signboards",
				price: "от 5 000 руб",
			},
			{
				image: interiorSign,
				alt: "Интерьерные вывески",
				text: "Интерьерные вывески",
				logo: "",
				color: "rgba(45, 17, 10, 0.79)",
				path: "services/interior-signs",
				price: "от 2 000 руб",
			},
			{
				image: card2,
				alt: "Объёмные буквы",
				text: "Объёмные буквы",
				logo: "",
				color: "rgba(62, 54, 36, 0.79)",
				path: "services/volume-letters",
				price: "от 80 руб/см",
			},
			{
				image: lightBoxes,
				alt: "Световые короба",
				text: "Световые короба",
				logo: "",
				color: "rgba(0, 11, 48, 0.79)",
				path: "services/light-boxes",
				price: "от 9 000 руб/м",
			},
			{
				image: card3,
				alt: "card3",
				text: "Гибкий неон",
				logo: "",
				color: "rgba(80, 10, 10, 0.79)",
				path: "services/flexible-neon",
				price: "от 2000 руб",
			},
			{
				image: card12,
				alt: "card12",
				text: "Панель-кронштейны",
				logo: "",
				color: "rgba(20, 23, 51, 0.79)",
				path: "services/panel-brackets",
				price: "от 8 000 руб",
			},
			{
				image: roofInstall,
				alt: "Крышные установки",
				text: "Крышные установки",
				logo: "",
				color: "rgba(0, 59, 78, 0.79)",
				path: "services/roof-install",
				price: "от 15 000 руб",
			},
			{
				image: windowDressing,
				alt: "Оформление витрин",
				text: "Оформление витрин",
				logo: "",
				color: "rgba(22, 80, 76, 0.79)",
				path: "services/window-dressing",
				price: "от 1 000 руб",
			},
			{
				image: pilons,
				alt: "Пилоны и стеллы",
				text: "Пилоны и стеллы",
				logo: "",
				color: "rgba(0, 61, 152, 0.79)",
				path: "services/pilons",
				price: "от 30 000 руб",
			},
			{
				image: card5,
				alt: "card5",
				text: "Брендирование транспорта",
				logo: "",
				color: "rgba(0, 59, 78, 0.79)",
				path: "services/branding-transport",
				price: "от 1500 руб",
			},
			{
				image: sequins,
				alt: "Живая реклама",
				text: "Живая реклама (пайетки)",
				logo: "",
				color: "rgba(120, 27, 14, 0.79)",
				path: "services/sequins",
				price: "от 10 000 руб",
			},
			{
				image: card6,
				alt: "card6",
				text: "Стенды",
				logo: "",
				color: "rgba(20, 23, 51, 0.79)",
				path: "services/stands",
				price: "от 1000 руб",
			},
			{
				image: card10,
				alt: "card10",
				text: "Таблички",
				logo: "",
				color: "rgba(57, 97, 100, 0.79)",
				path: "services/tables",
				price: "от 300 руб",
			},
			{
				image: slimPanels,
				alt: "Тонкие световые панели",
				text: "Тонкие световые панели",
				logo: "",
				color: "rgba(64, 89, 11, 0.79)",
				path: "services/slim-panels",
				price: "от 5 000 руб",
			},
			{
				image: card4,
				alt: "card4",
				text: "Согласование рекламы",
				logo: "",
				color: "rgba(142, 149, 13, 0.79)",
				path: "services/advertion-production",
				price: "от 1 000 руб",
			},
			{
				image: serviceMain,
				alt: "Сервисное обслуживание",
				text: "Сервисное обслуживание",
				logo: "",
				color: "rgba(55, 103, 63, 0.79)",
				path: "services/service-main",
				price: "от 1 000 руб",
			},
			{
				image: laserCutting,
				alt: "Лазерная резка и гравировка",
				text: "Лазерная резка и гравировка",
				logo: "",
				color: "rgba(0, 27, 78, 0.79)",
				path: "services/laser-cutting",
				price: "от 50 руб м.п.",
			},
			{
				image: card11,
				alt: "card11",
				text: "Фрезеровка",
				logo: "",
				color: "rgba(118, 71, 0, 0.79)",
				path: "services/milling",
				price: "от 30 руб",
			},
		],
	},
	{
		theme: "light",
		textTheme: "text-dark",
		direction: "flex-row-reverse",
		titleSize: "light",
		titleColSize: "col-lg-9",
		id: "printing",
		title: "Печать широкорматная, интерьерная , УФ",
		list: [
			{
				image: card8,
				alt: "card8",
				text: "Широко-форматная печать",
				logo: "images/wideprint-icon.svg",
				color: "rgba(0, 172, 216, 0.79)",
				path: "services/widescreen-print",
				price: "от 300 руб",
			},
			{
				image: plotterCutting,
				alt: "Плоттерная резка",
				text: "Плоттерная резка",
				logo: "",
				color: "rgba(45, 17, 10, 0.79)",
				path: "services/plotter-cutting",
				price: "от 500 руб",
			},
			{
				image: card9,
				alt: "card9",
				text: "Стикеры",
				logo: "",
				color: "rgba(55, 103, 63, 0.79)",
				path: "services/stickers",
				price: "от 10 руб/шт",
			},
			{
				image: card7,
				alt: "card7",
				text: "УФ печать",
				logo: "",
				color: "rgba(95, 23, 152, 0.79)",
				path: "services/uv-print",
				price: "от 500 руб",
			},
			{
				image: interiorPrint,
				alt: "Интерьерная печать",
				text: "Интерьерная печать",
				logo: "",
				color: "rgba(80, 22, 22, 0.79)",
				path: "services/uv-print",
				price: "от 350 руб",
			},
		],
	},
	{
		theme: "dark",
		textTheme: "text-dark",
		direction: "flex-row",
		titleSize: "small",
		titleColSize: "col-lg-6",
		id: "polygraphy",
		title: "Полиграфические услуги",
		list: [
			{
				image: bussinessCard,
				alt: "Визитки",
				text: "Визитки",
				logo: "",
				color: "rgba(0, 172, 216, 0.79)",
				id: "signboards",
				path: "services/business-card",
				price: "от 600 руб",
			},
			{
				image: flyers,
				alt: "Флаеры, листовки",
				text: "Флаеры, листовки",
				logo: "",
				color: "rgba(130, 175, 0, 0.79)",
				path: "services/flyers",
				price: "от 1000 руб",
			},
			{
				image: badges,
				alt: "Бейджи",
				text: "Бейджи",
				logo: "",
				color: "rgba(0, 59, 78, 0.79)",
				path: "services/badges",
				price: "от 250 руб",
			},
			{
				image: calendars,
				alt: "Календари",
				text: "Календари",
				logo: "",
				color: "rgba(80, 22, 22, 0.79)",
				path: "services/calendars",
				price: "от 200 руб",
			},
			{
				image: plasticCards,
				alt: "Пластиковые карты",
				text: "Пластиковые карты",
				logo: "",
				color: "rgba(50, 50, 51, 0.79)",
				path: "services/plastic-cards",
				price: "от 20 руб",
			},
			{
				image: menus,
				alt: "Меню для кафе и ресторанов",
				text: "Меню для кафе и ресторанов",
				logo: "",
				color: "rgba(99, 76, 59, 0.79)",
				path: "services/menus",
				price: "от 500 руб",
			},
			{
				image: souvenirs,
				alt: "Сувенирная продукция",
				text: "Сувенирная продукция",
				logo: "",
				color: "rgba(80, 31, 220, 0.79)",
				path: "services/souvenirs",
				price: "от 200 руб",
			},
			{
				image: packets,
				alt: "Пакеты",
				text: "Пакеты",
				logo: "",
				color: "rgba(220, 190, 31, 0.79)",
				path: "services/package",
				price: "от 10 руб",
			},
			{
				image: digitalPrint,
				alt: "Оперативная цифровая печать",
				text: "Оперативная цифровая печать",
				logo: "",
				color: "rgba(55, 103, 63, 0.79)",
				path: "services/digital-print",
				price: "от 500 руб",
			},
			{
				image: offsetPrint,
				alt: "Офсетная печать",
				text: "Офсетная печать",
				logo: "",
				color: "rgba(37, 33, 48, 0.79)",
				path: "services/offset-print",
				price: "от 1000 руб",
			},
		],
	},
];

export const advertionProductionData = {
	theme: "dark",
	textTheme: "white",
	direction: "flex-row",
	title: "Производство рекламы",
	list: [
		{
			image: card1,
			alt: "card1",
			text: "Вывески",
			logo: "images/banner-icon.svg",
			color: "rgba(235, 167, 7, 0.79)",
			path: "",
			price: "от 5 000 руб",
		},
		{
			image: card12,
			alt: "card12",
			text: "Панель-кронштейны",
			logo: "",
			color: "rgba(20, 23, 51, 0.79)",
			path: "",
			price: "от 8 000 руб",
		},
	],
};
